// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyD_ZBq5fQltSA1nRqlybZc84i52dipDCGc",
  authDomain: "todo-33557.firebaseapp.com",
  projectId: "todo-33557",
  storageBucket: "todo-33557.appspot.com",
  messagingSenderId: "602847530388",
  appId: "1:602847530388:web:f3dd715ccdff22aec81381"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

export default firebaseConfig